services:
  app:
    build: .
    container_name: python_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=teste
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
